use doctoyou;

-- providers data

CALL add_provider('Alice', 'Smith', 'F', 'Doctor', 9876543210, 'alice@hospital.com', 'securepass', 'DOC12345', 'Cardiology', NULL, NULL);
CALL add_provider('Bob', 'Jones', 'M', 'Nurse', 9876543211, 'bob@nurse.com', 'securepass', NULL, NULL, 'NUR67890', 'Emergency');
CALL add_provider('Charlie', 'Brown', 'M', 'Caretaker', 9876543212, 'charlie@care.com', 'securepass', NULL, NULL, NULL, NULL);
CALL add_provider('Diana', 'Prince', 'F', 'Doctor', 9876543213, 'diana@hospital.com', 'securepass', 'DOC12346', 'Neurology', NULL, NULL);
CALL add_provider('Ethan', 'Hunt', 'M', 'Nurse', 9876543214, 'ethan@nurse.com', 'securepass', NULL, NULL, 'NUR67891', 'ICU');
CALL add_provider('Fiona', 'Gallagher', 'F', 'Caretaker', 9876543215, 'fiona@care.com', 'securepass', NULL, NULL, NULL, NULL);
CALL add_provider('George', 'Miller', 'M', 'Doctor', 9876543216, 'george@hospital.com', 'securepass', 'DOC12347', 'Orthopedics', NULL, NULL);
CALL add_provider('Hannah', 'Lee', 'F', 'Nurse', 9876543217, 'hannah@nurse.com', 'securepass', NULL, NULL, 'NUR67892', 'Pediatrics');
CALL add_provider('Ian', 'Wright', 'M', 'Caretaker', 9876543218, 'ian@care.com', 'securepass', NULL, NULL, NULL, NULL);
CALL add_provider('Jasmine', 'Khan', 'F', 'Doctor', 9876543219, 'jasmine@hospital.com', 'securepass', 'DOC12348', 'Dermatology', NULL, NULL);
CALL add_provider('Kevin', 'Tran', 'M', 'Nurse', 9876543220, 'kevin@nurse.com', 'securepass', NULL, NULL, 'NUR67893', 'Surgery');
CALL add_provider('Lily', 'Chen', 'F', 'Caretaker', 9876543221, 'lily@care.com', 'securepass', NULL, NULL, NULL, NULL);
CALL add_provider('Marcus', 'Bell', 'M', 'Doctor', 9876543222, 'marcus@hospital.com', 'securepass', 'DOC12349', 'Radiology', NULL, NULL);
CALL add_provider('Nina', 'Patel', 'F', 'Nurse', 9876543223, 'nina@nurse.com', 'securepass', NULL, NULL, 'NUR67894', 'Oncology');
CALL add_provider('Oscar', 'Grant', 'M', 'Caretaker', 9876543224, 'oscar@care.com', 'securepass', NULL, NULL, NULL, NULL);
CALL add_provider('Paula', 'Ramirez', 'F', 'Doctor', 9876543225, 'paula@hospital.com', 'securepass', 'DOC12350', 'Gastroenterology', NULL, NULL);
CALL add_provider('Quentin', 'Stone', 'M', 'Nurse', 9876543226, 'quentin@nurse.com', 'securepass', NULL, NULL, 'NUR67895', 'Trauma');
CALL add_provider('Rita', 'Singh', 'F', 'Caretaker', 9876543227, 'rita@care.com', 'securepass', NULL, NULL, NULL, NULL);
CALL add_provider('Sam', 'Wilson', 'M', 'Doctor', 9876543228, 'sam@hospital.com', 'securepass', 'DOC12351', 'Urology', NULL, NULL);
CALL add_provider('Tina', 'Nguyen', 'F', 'Nurse', 9876543229, 'tina@nurse.com', 'securepass', NULL, NULL, 'NUR67896', 'Neonatal');
CALL add_provider('Uma', 'Desai', 'F', 'Caretaker', 9876543230, 'uma@care.com', 'securepass', NULL, NULL, NULL, NULL);
CALL add_provider('Victor', 'Lopez', 'M', 'Doctor', 9876543231, 'victor@hospital.com', 'securepass', 'DOC12352', 'Pulmonology', NULL, NULL);
CALL add_provider('Wendy', 'Kim', 'F', 'Nurse', 9876543232, 'wendy@nurse.com', 'securepass', NULL, NULL, 'NUR67897', 'Rehab');
CALL add_provider('Xavier', 'Clark', 'M', 'Caretaker', 9876543233, 'xavier@care.com', 'securepass', NULL, NULL, NULL, NULL);
CALL add_provider('Yara', 'Ali', 'F', 'Doctor', 9876543234, 'yara@hospital.com', 'securepass', 'DOC12353', 'Endocrinology', NULL, NULL);
CALL add_provider('Zane', 'Baker', 'M', 'Nurse', 9876543235, 'zane@nurse.com', 'securepass', NULL, NULL, 'NUR67898', 'Burn Unit');
CALL add_provider('Ava', 'Morgan', 'F', 'Caretaker', 9876543236, 'ava@care.com', 'securepass', NULL, NULL, NULL, NULL);
CALL add_provider('Ben', 'Foster', 'M', 'Doctor', 9876543237, 'ben@hospital.com', 'securepass', 'DOC12354', 'Hematology', NULL, NULL);
CALL add_provider('Clara', 'Diaz', 'F', 'Nurse', 9876543238, 'clara@nurse.com', 'securepass', NULL, NULL, 'NUR67899', 'Ambulatory');
CALL add_provider('David', 'Young', 'M', 'Caretaker', 9876543239, 'david@care.com', 'securepass', NULL, NULL, NULL, NULL);
CALL add_provider('Ella', 'Reed', 'F', 'Doctor', 9876543240, 'ella@hospital.com', 'securepass', 'DOC12355', 'Nephrology', NULL, NULL);
CALL add_provider('Frank', 'Carter', 'M', 'Nurse', 9876543241, 'frank@nurse.com', 'securepass', NULL, NULL, 'NUR67900', 'Stroke Unit');
CALL add_provider('Grace', 'Watson', 'F', 'Caretaker', 9876543242, 'grace@care.com', 'securepass', NULL, NULL, NULL, NULL);
CALL add_provider('Henry', 'Brooks', 'M', 'Doctor', 9876543243, 'henry@hospital.com', 'securepass', 'DOC12356', 'Ophthalmology', NULL, NULL);
CALL add_provider('Isla', 'Ford', 'F', 'Nurse', 9876543244, 'isla@nurse.com', 'securepass', NULL, NULL, 'NUR67901', 'Recovery');
CALL add_provider('Jack', 'Evans', 'M', 'Caretaker', 9876543245, 'jack@care.com', 'securepass', NULL, NULL, NULL, NULL);
CALL add_provider('Kara', 'Murphy', 'F', 'Doctor', 9876543246, 'kara@hospital.com', 'securepass', 'DOC12357', 'ENT', NULL, NULL);
CALL add_provider('Leo', 'Ward', 'M', 'Nurse', 9876543247, 'leo@nurse.com', 'securepass', NULL, NULL, 'NUR67902', 'Anesthesiology');
CALL add_provider('Maya', 'Cole', 'F', 'Caretaker', 9876543248, 'maya@care.com', 'securepass', NULL, NULL, NULL, NULL);
CALL add_provider('Noah', 'Perry', 'M', 'Doctor', 9876543249, 'noah@hospital.com', 'securepass', 'DOC12358', 'Pathology', NULL, NULL);
CALL add_provider('Olivia', 'Russell', 'F', 'Nurse', 9876543250, 'olivia@nurse.com', 'securepass', NULL, NULL, 'NUR67903', 'Outpatient');
CALL add_provider('Peter', 'Barnes', 'M', 'Caretaker', 9876543251, 'peter@care.com', 'securepass', NULL, NULL, NULL, NULL);
CALL add_provider('Queenie', 'Stewart', 'F', 'Doctor', 9876543252, 'queenie@hospital.com', 'securepass', 'DOC12359', 'Rheumatology', NULL, NULL);
CALL add_provider('Ryan', 'Hughes', 'M', 'Nurse', 9876343253, 'ryan@nurse.com', 'securepass', NULL, NULL, 'NUR6902', 'Anesthesiology');

-- User data

INSERT INTO users (fname, lname, gender, phone, email, password) VALUES ('Aarav', 'Sharma', 'M', 9000000000, 'aarav.sharma@example.com', 'securepass');
INSERT INTO users (fname, lname, gender, phone, email, password) VALUES ('Aanya', 'Verma', 'F', 9000000001, 'aanya.verma@example.com', 'securepass');
INSERT INTO users (fname, lname, gender, phone, email, password) VALUES ('Vihaan', 'Reddy', 'M', 9000000002, 'vihaan.reddy@example.com', 'securepass');
INSERT INTO users (fname, lname, gender, phone, email, password) VALUES ('Ishita', 'Patel', 'F', 9000000003, 'ishita.patel@example.com', 'securepass');
INSERT INTO users (fname, lname, gender, phone, email, password) VALUES ('Aditya', 'Mehta', 'M', 9000000004, 'aditya.mehta@example.com', 'securepass');
INSERT INTO users (fname, lname, gender, phone, email, password) VALUES ('Kavya', 'Joshi', 'F', 9000000005, 'kavya.joshi@example.com', 'securepass');
INSERT INTO users (fname, lname, gender, phone, email, password) VALUES ('Rohan', 'Nair', 'M', 9000000006, 'rohan.nair@example.com', 'securepass');
INSERT INTO users (fname, lname, gender, phone, email, password) VALUES ('Sneha', 'Kumar', 'F', 9000000007, 'sneha.kumar@example.com', 'securepass');
INSERT INTO users (fname, lname, gender, phone, email, password) VALUES ('Aryan', 'Gupta', 'M', 9000000008, 'aryan.gupta@example.com', 'securepass');
INSERT INTO users (fname, lname, gender, phone, email, password) VALUES ('Meera', 'Singh', 'F', 9000000009, 'meera.singh@example.com', 'securepass');
INSERT INTO users (fname, lname, gender, phone, email, password) VALUES ('Raj', 'Choudhary', 'M', 9000000010, 'raj.choudhary@example.com', 'securepass');
INSERT INTO users (fname, lname, gender, phone, email, password) VALUES ('Neha', 'Yadav', 'F', 9000000011, 'neha.yadav@example.com', 'securepass');
INSERT INTO users (fname, lname, gender, phone, email, password) VALUES ('Arjun', 'Mishra', 'M', 9000000012, 'arjun.mishra@example.com', 'securepass');
INSERT INTO users (fname, lname, gender, phone, email, password) VALUES ('Pooja', 'Rana', 'F', 9000000013, 'pooja.rana@example.com', 'securepass');
INSERT INTO users (fname, lname, gender, phone, email, password) VALUES ('Karan', 'Thakur', 'M', 9000000014, 'karan.thakur@example.com', 'securepass');
INSERT INTO users (fname, lname, gender, phone, email, password) VALUES ('Divya', 'Bansal', 'F', 9000000015, 'divya.bansal@example.com', 'securepass');
INSERT INTO users (fname, lname, gender, phone, email, password) VALUES ('Manish', 'Goyal', 'M', 9000000016, 'manish.goyal@example.com', 'securepass');
INSERT INTO users (fname, lname, gender, phone, email, password) VALUES ('Ritika', 'Malhotra', 'F', 9000000017, 'ritika.malhotra@example.com', 'securepass');
INSERT INTO users (fname, lname, gender, phone, email, password) VALUES ('Siddharth', 'Kapoor', 'M', 9000000018, 'siddharth.kapoor@example.com', 'securepass');
INSERT INTO users (fname, lname, gender, phone, email, password) VALUES ('Anjali', 'Saxena', 'F', 9000000019, 'anjali.saxena@example.com', 'securepass');
INSERT INTO users (fname, lname, gender, phone, email, password) VALUES ('Tushar', 'Reddy', 'M', 9000000020, 'tushar.reddy@example.com', 'securepass');
INSERT INTO users (fname, lname, gender, phone, email, password) VALUES ('Nidhi', 'Sharma', 'F', 9000000021, 'nidhi.sharma@example.com', 'securepass');
INSERT INTO users (fname, lname, gender, phone, email, password) VALUES ('Harsh', 'Verma', 'M', 9000000022, 'harsh.verma@example.com', 'securepass');
INSERT INTO users (fname, lname, gender, phone, email, password) VALUES ('Priya', 'Patel', 'F', 9000000023, 'priya.patel@example.com', 'securepass');
INSERT INTO users (fname, lname, gender, phone, email, password) VALUES ('Yash', 'Mehta', 'M', 9000000024, 'yash.mehta@example.com', 'securepass');
INSERT INTO users (fname, lname, gender, phone, email, password) VALUES ('Riya', 'Joshi', 'F', 9000000025, 'riya.joshi@example.com', 'securepass');
INSERT INTO users (fname, lname, gender, phone, email, password) VALUES ('Aman', 'Nair', 'M', 9000000026, 'aman.nair@example.com', 'securepass');
INSERT INTO users (fname, lname, gender, phone, email, password) VALUES ('Shruti', 'Kumar', 'F', 9000000027, 'shruti.kumar@example.com', 'securepass');
INSERT INTO users (fname, lname, gender, phone, email, password) VALUES ('Raghav', 'Gupta', 'M', 9000000028, 'raghav.gupta@example.com', 'securepass');
INSERT INTO users (fname, lname, gender, phone, email, password) VALUES ('Simran', 'Singh', 'F', 9000000029, 'simran.singh@example.com', 'securepass');
INSERT INTO users (fname, lname, gender, phone, email, password) VALUES ('Mohit', 'Choudhary', 'M', 9000000030, 'mohit.choudhary@example.com', 'securepass');
INSERT INTO users (fname, lname, gender, phone, email, password) VALUES ('Tanvi', 'Yadav', 'F', 9000000031, 'tanvi.yadav@example.com', 'securepass');
INSERT INTO users (fname, lname, gender, phone, email, password) VALUES ('Abhishek', 'Mishra', 'M', 9000000032, 'abhishek.mishra@example.com', 'securepass');
INSERT INTO users (fname, lname, gender, phone, email, password) VALUES ('Kriti', 'Rana', 'F', 9000000033, 'kriti.rana@example.com', 'securepass');
INSERT INTO users (fname, lname, gender, phone, email, password) VALUES ('Varun', 'Thakur', 'M', 9000000034, 'varun.thakur@example.com', 'securepass');
INSERT INTO users (fname, lname, gender, phone, email, password) VALUES ('Aishwarya', 'Bansal', 'F', 9000000035, 'aishwarya.bansal@example.com', 'securepass');
INSERT INTO users (fname, lname, gender, phone, email, password) VALUES ('Nikhil', 'Goyal', 'M', 9000000036, 'nikhil.goyal@example.com', 'securepass');
INSERT INTO users (fname, lname, gender, phone, email, password) VALUES ('Sakshi', 'Malhotra', 'F', 9000000037, 'sakshi.malhotra@example.com', 'securepass');
INSERT INTO users (fname, lname, gender, phone, email, password) VALUES ('Rahul', 'Kapoor', 'M', 9000000038, 'rahul.kapoor@example.com', 'securepass');

INSERT INTO users (fname, lname, gender, phone, email, password) VALUES ('Alice', 'Smith', 'F', 9876543210, 'alice@hospital.com', 'securepass');
INSERT INTO users (fname, lname, gender, phone, email, password) VALUES ('Bob', 'Jones', 'M', 9876543211, 'bob@nurse.com', 'securepass');
INSERT INTO users (fname, lname, gender, phone, email, password) VALUES ('Charlie', 'Brown', 'M', 9876543212, 'charlie@care.com', 'securepass');
INSERT INTO users (fname, lname, gender, phone, email, password) VALUES ('Diana', 'Prince', 'F', 9876543213, 'diana@hospital.com', 'securepass');
INSERT INTO users (fname, lname, gender, phone, email, password) VALUES ('Ethan', 'Hunt', 'M', 9876543214, 'ethan@nurse.com', 'securepass');
INSERT INTO users (fname, lname, gender, phone, email, password) VALUES ('Fiona', 'Gallagher', 'F', 9876543215, 'fiona@care.com', 'securepass');
INSERT INTO users (fname, lname, gender, phone, email, password) VALUES ('George', 'Miller', 'M', 9876543216, 'george@hospital.com', 'securepass');
INSERT INTO users (fname, lname, gender, phone, email, password) VALUES ('Hannah', 'Lee', 'F', 9876543217, 'hannah@nurse.com', 'securepass');
INSERT INTO users (fname, lname, gender, phone, email, password) VALUES ('Ian', 'Wright', 'M', 9876543218, 'ian@care.com', 'securepass');
INSERT INTO users (fname, lname, gender, phone, email, password) VALUES ('Jasmine', 'Khan', 'F', 9876543219, 'jasmine@hospital.com', 'securepass');
INSERT INTO users VALUES (NULL, 'Kevin', 'Tran', 'M', 9876543220, 'kevin@nurse.com', 'securepass', DEFAULT);
INSERT INTO users VALUES (NULL, 'Lily', 'Chen', 'F', 9876543221, 'lily@care.com', 'securepass', DEFAULT);
INSERT INTO users VALUES (NULL, 'Marcus', 'Bell', 'M', 9876543222, 'marcus@hospital.com', 'securepass', DEFAULT);
INSERT INTO users VALUES (NULL, 'Nina', 'Patel', 'F', 9876543223, 'nina@nurse.com', 'securepass', DEFAULT);
INSERT INTO users VALUES (NULL, 'Oscar', 'Grant', 'M', 9876543224, 'oscar@care.com', 'securepass', DEFAULT);
INSERT INTO users VALUES (NULL, 'Paula', 'Ramirez', 'F', 9876543225, 'paula@hospital.com', 'securepass', DEFAULT);
INSERT INTO users VALUES (NULL, 'Quentin', 'Stone', 'M', 9876543226, 'quentin@nurse.com', 'securepass', DEFAULT);
INSERT INTO users VALUES (NULL, 'Rita', 'Singh', 'F', 9876543227, 'rita@care.com', 'securepass', DEFAULT);
INSERT INTO users VALUES (NULL, 'Sam', 'Wilson', 'M', 9876543228, 'sam@hospital.com', 'securepass', DEFAULT);
INSERT INTO users VALUES (NULL, 'Tina', 'Nguyen', 'F', 9876543229, 'tina@nurse.com', 'securepass', DEFAULT);
INSERT INTO users VALUES (NULL, 'Uma', 'Desai', 'F', 9876543230, 'uma@care.com', 'securepass', DEFAULT);
INSERT INTO users VALUES (NULL, 'Victor', 'Lopez', 'M', 9876543231, 'victor@hospital.com', 'securepass', DEFAULT);
INSERT INTO users VALUES (NULL, 'Wendy', 'Kim', 'F', 9876543232, 'wendy@nurse.com', 'securepass', DEFAULT);
INSERT INTO users VALUES (NULL, 'Xavier', 'Clark', 'M', 9876543233, 'xavier@care.com', 'securepass', DEFAULT);
INSERT INTO users VALUES (NULL, 'Yara', 'Ali', 'F', 9876543234, 'yara@hospital.com', 'securepass', DEFAULT);
INSERT INTO users VALUES (NULL, 'Zane', 'Baker', 'M', 9876543235, 'zane@nurse.com', 'securepass', DEFAULT);
INSERT INTO users VALUES (NULL, 'Ava', 'Morgan', 'F', 9876543236, 'ava@care.com', 'securepass', DEFAULT);
INSERT INTO users VALUES (NULL, 'Ben', 'Foster', 'M', 9876543237, 'ben@hospital.com', 'securepass', DEFAULT);
INSERT INTO users VALUES (NULL, 'Clara', 'Diaz', 'F', 9876543238, 'clara@nurse.com', 'securepass', DEFAULT);
INSERT INTO users VALUES (NULL, 'David', 'Young', 'M', 9876543239, 'david@care.com', 'securepass', DEFAULT);
